// Call-event pipeline: everything that turns a normalized provider event into
// a row in `calls`, plus the downstream effects that row triggers (summary,
// campaign outcome, outgoing webhook). Shared by the webhook route, the
// background drain, and the admin backfill.
//
// This file is deliberately PROVIDER-NEUTRAL. It never sees a provider's field
// names — drivers hand it the shape described in services/voice/provider.js.
// Adding or swapping a provider must not require an edit here.
const crypto = require('crypto');
const { sql } = require('../db');
const { summarize } = require('../summarize');
const { logger } = require('../lib/logger');
const { sendCallCompleted } = require('./outbound-webhook');
const { encryptField } = require('../lib/pii');
const { runWithContext } = require('../lib/tenant-context');
const voice = require('./voice');

// A summary is only useful to a Saudi sales team in Arabic. The provider's
// post-call summariser is not guaranteed to answer in the conversation's
// language, so a summary with no Arabic letters in it is treated as missing
// and regenerated by our own summariser — same rule as a too-short one.
const ARABIC_RE = /[؀-ۿ]/;

function needsOwnSummary(providerSummary, transcript) {
  if (!transcript) return false;
  const s = String(providerSummary || '').trim();
  if (s.length < 20) return true;
  return !ARABIC_RE.test(s) && ARABIC_RE.test(transcript);
}

/**
 * Resolve which company a call belongs to. Delegated to the driver because the
 * identifiers differ per provider, but the RULE does not: only signals the
 * PROVIDER controls are trusted. Anything a caller, a client or the language
 * model could have chosen is cross-checked, never taken at face value.
 */
async function resolveCompany(ev, log) {
  const driver = voice.driverByName(ev?.provider);
  if (!driver?.resolveCompanyForEvent) return null;
  return driver.resolveCompanyForEvent(ev, log);
}

/**
 * Persist one normalized call event and run everything that hangs off it.
 * Idempotent: upsertCall is keyed on the provider call id, and every effect
 * below is safe to repeat (setCallSummary overwrites, handleCallEnded matches
 * on call id, the outgoing webhook is at-least-once by design).
 */
async function processCallEvent(ev, log) {
  if (!ev || !ev.providerCallId) return null;

  const companyId = ev.companyId || await resolveCompany(ev, log);

  await sql.upsertCall.run({
    id            : ev.providerCallId,
    company_id    : companyId || null,
    assistant_id  : ev.agentId || null,
    caller_number : encryptField(ev.callerNumber || null),
    duration_sec  : ev.durationSec ?? null,
    started_at    : ev.startedAt || null,
    ended_at      : ev.endedAt || null,
    ended_reason  : ev.endedReason || null,
    transcript    : ev.transcript || null,
    summary       : ev.summary || null,
    cost_usd      : ev.costUsd ?? null,
    cost_credits  : ev.costCredits ?? null,
    // null means "the provider did not say" — upsertCall COALESCEs it so an
    // outbound stub is never silently relabelled inbound.
    direction     : ev.direction || null,
    recording_url : ev.recordingUrl || null,
    structured_data: ev.structuredData ? JSON.stringify(ev.structuredData) : null,
    provider      : ev.provider || null,
    provider_call_ref: ev.providerCallRef || null,
    has_recording : ev.hasRecording ? 1 : 0,
  });

  // Nothing below applies until the call is actually over.
  if (!ev.isFinal) return companyId || null;

  if (needsOwnSummary(ev.summary, ev.transcript)) {
    const ours = await summarize(ev.transcript);
    if (ours) await sql.setCallSummary.run(ours, ev.providerCallId);
  }

  // If this call belongs to a campaign contact, resolve its outcome.
  try {
    const { handleCallEnded } = require('./campaigns'); // lazy: avoid require cycle
    await handleCallEnded(ev.providerCallId, ev.endedReason, ev.durationSec);
  } catch (e) {
    logger.warn('campaign call-ended hook failed', { err: e.message });
  }

  // Outgoing webhook (opt-in per company). Read the row back so the payload
  // carries the final summary, then fire-and-forget.
  if (companyId) {
    try {
      const { loadCompany } = require('../companies'); // lazy: avoids require cycle at module load
      const company = await loadCompany(companyId);
      const finalRow = await sql.getCall.get(ev.providerCallId);
      if (company && finalRow) sendCallCompleted(company, finalRow);
    } catch (e) {
      logger.warn('outbound webhook dispatch skipped', { err: e.message });
    }
  }

  return companyId || null;
}

/**
 * Parse a stored raw webhook body with the right driver and process it.
 * Used by the drain; the live route normalizes before it ever stores.
 */
async function processStoredEvent(row) {
  const driver = voice.driverByName(row.provider);
  if (!driver) {
    // A pending event from a provider this build no longer ships (a Vapi event
    // left in the inbox across the migration deploy). The raw body is kept —
    // only the status changes — so nothing is lost and the drain stops
    // retrying it forever.
    await sql.markWebhookSkipped.run(`no driver for provider "${row.provider}"`, row.id);
    logger.warn('webhook drain: parked event from a removed provider', {
      eventId: row.id, provider: row.provider,
    });
    return null;
  }
  const parsed = JSON.parse(row.raw_body);
  const ev = driver.normalizeEvent(parsed);
  if (!ev) return null;                 // nothing to persist (e.g. an audio blob)
  return processCallEvent(ev);
}

// Drain up to N pending webhook events on a tick. Called from the webhook
// route after each event and from the background timer below.
async function drainWebhookInbox(limit = 5) {
  const pending = await sql.listPendingWebhooks.all(limit);
  for (const ev of pending) {
    try {
      await processStoredEvent(ev);
      // A skipped row already has a terminal status; marking it processed too
      // would be harmless but misleading, so only mark rows we really handled.
      if (ev.provider && voice.driverByName(ev.provider)) {
        await sql.markWebhookProcessed.run(ev.id);
      }
    } catch (e) {
      await sql.markWebhookFailed.run(e.message?.slice(0, 500) || 'unknown', ev.id);
      logger.error('webhook drain failed', { eventId: ev.id, err: e.message });
    }
  }
}

// Background drain every 60s. Without this, a failed event only got retried
// when the NEXT webhook arrived — an evening failure could sit unprocessed
// until the next morning's first call. unref() so it never blocks shutdown.
//
// Runs OUTSIDE any HTTP request, so — like the campaign worker — it has no RLS
// tenant context. Its work (upsertCall into `calls`, handleCallEnded into
// `campaign_contacts`) touches FORCE-RLS tables that fail closed, so without an
// explicit context a retried end-of-call event would silently update ZERO rows
// and the campaign contact would stay stuck in `calling` until the 30-min stale
// sweep force-failed it (mislabelling a connected call as "invalid"). The event
// is cross-tenant (each event resolves its own company), so drain under the
// system bypass — the same context the webhook HTTP route already has.
function startDrainTimer() {
  const t = setInterval(() => {
    runWithContext({ bypass: true, companyId: null },
      () => drainWebhookInbox(10)).catch((e) => logger.error('scheduled drain failed', { err: e.message }));
  }, 60_000);
  t.unref();
  return t;
}

/**
 * Pull the most recent calls straight from the provider and upsert them,
 * catching anything the webhook missed. Returns { fetched, matched }.
 */
async function backfillRecentCalls(limit = 50) {
  const driver = voice.DRIVERS[voice.DEFAULT_PROVIDER];
  const events = await driver.listRecentCalls(limit);
  let matched = 0;
  for (const ev of events) {
    const companyId = await processCallEvent(ev);
    if (companyId) matched++;
  }
  return { fetched: events.length, matched };
}

/**
 * Refresh one stored call from the provider. Used when a row is still a stub
 * (no transcript or no ended_reason) because its webhook has not landed — or
 * never will. Returns the refreshed row, or the original on failure.
 */
async function refreshCall(callRow) {
  if (!callRow?.id) return callRow;
  const driver = voice.forCall(callRow);
  const ev = await driver.fetchCall(callRow.id);
  if (!ev) return callRow;
  // Keep the company we already resolved; re-resolving could null it out if the
  // agent has since been recreated.
  ev.companyId = callRow.company_id || null;
  await processCallEvent(ev);
  return sql.getCall.get(callRow.id);
}

/** Stable id for a call we originate before the provider names it. */
const newCallId = () => crypto.randomUUID();

/**
 * A link to a call's audio that the reader can actually open, or null.
 *
 * Historical rows hold a real provider URL and keep it. Rows from the current
 * provider hold NONE: its audio is served from an authenticated API, so no
 * shareable link exists, and putting a provider-scoped identifier into a field
 * named `recording_url` would leak an internal token into CSV exports and
 * outgoing webhooks. For those we return our own proxy endpoint, which is
 * session-authenticated — correct for an operator, deliberately useless to an
 * anonymous fetcher.
 *
 * NOT used for the outgoing customer webhook: the receiver has no session, so
 * that payload reports `recording_url: null` plus a `has_recording` flag
 * instead of a link it could never fetch.
 */
function recordingLinkFor(callRow, baseUrl = process.env.PUBLIC_BASE_URL) {
  if (!callRow) return null;
  if (callRow.recording_url) return callRow.recording_url;
  if (!callRow.has_recording) return null;
  const base = String(baseUrl || '').replace(/\/+$/, '');
  if (!base) return null;
  return `${base}/api/calls/${encodeURIComponent(callRow.id)}/recording`;
}

module.exports = {
  processCallEvent,
  processStoredEvent,
  drainWebhookInbox,
  startDrainTimer,
  backfillRecentCalls,
  refreshCall,
  resolveCompany,
  needsOwnSummary,
  newCallId,
  recordingLinkFor,
};
