// SQLite → PostgreSQL (+pgvector) migration.
//
// Usage:
//   DATABASE_URL=postgres://... node scripts/migrate-to-pg.js [--sqlite path/to/data.db]
//
// Idempotent full copy: creates the schema (IF NOT EXISTS), TRUNCATEs the
// target tables, copies every row, fixes sequences, adds FK constraints,
// builds the pgvector HNSW index, then VERIFIES:
//   1. row counts match per table
//   2. pgvector cosine top-K matches the current JS cosine top-K for
//      sample embeddings (proves the vector conversion is faithful)
//
// Design notes:
// - Timestamp columns stay TEXT ('YYYY-MM-DD HH:MM:SS', UTC) — identical to
//   SQLite's datetime('now') — so every string-comparison query in the app
//   keeps its exact semantics after cutover.
// - kb_chunks.embedding: BLOB (Float32Array LE) → vector(1536).
// - Serial ids use GENERATED BY DEFAULT AS IDENTITY so migrated rows keep
//   their original ids; sequences are bumped to MAX(id)+1 afterwards.
const path = require('path');
const { Client } = require('pg');
const Database = require('better-sqlite3');

const argSqlite = process.argv.indexOf('--sqlite');
const SQLITE_PATH = argSqlite > -1
  ? process.argv[argSqlite + 1]
  : (process.env.DB_PATH || path.join(__dirname, '..', 'data.db'));
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('DATABASE_URL is required'); process.exit(1); }

const { DDL } = require('../db-pg-schema');

// Tables in copy order (no FK constraints during copy; added after).
const TABLES = [
  'schema_migrations', 'users', 'companies', 'sessions', 'auth_events',
  'chats', 'calls', 'kb_documents', 'kb_chunks', 'audit_events',
  'usage_counters', 'webhook_events', 'scenarios', 'scenario_versions',
  'whatsapp_sessions', 'api_keys', 'campaigns', 'campaign_contacts',
  'eval_questions', 'eval_runs',
];

// Serial-id tables that need their sequence bumped after explicit-id inserts.
const IDENTITY_TABLES = ['users', 'auth_events', 'chats', 'kb_documents',
  'kb_chunks', 'audit_events', 'webhook_events', 'scenarios',
  'scenario_versions', 'api_keys', 'campaigns', 'campaign_contacts',
  'eval_questions', 'eval_runs'];

function bufferToVec(buf) {
  return new Float32Array(buf.buffer, buf.byteOffset, buf.length / 4);
}
function vecLiteral(buf) {
  const v = bufferToVec(buf);
  // Full float precision — cosine parity with the JS implementation.
  return '[' + Array.from(v).join(',') + ']';
}

async function main() {
  console.log(`SQLite source : ${SQLITE_PATH}`);
  const sq = new Database(SQLITE_PATH, { readonly: true });
  const pg = new Client({ connectionString: DATABASE_URL });
  await pg.connect();
  console.log('Postgres connected');

  await pg.query(DDL);
  console.log('schema created');

  // Fresh copy every run (idempotent). CASCADE clears dependent rows.
  await pg.query(`TRUNCATE ${TABLES.join(', ')} CASCADE`);

  for (const table of TABLES) {
    const exists = sq.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(table);
    if (!exists) { console.log(`  ${table}: not in source, skipped`); continue; }
    const rows = sq.prepare(`SELECT * FROM ${table}`).all();
    if (!rows.length) { console.log(`  ${table}: 0 rows`); continue; }

    const cols = Object.keys(rows[0]);
    const colList = cols.map((c) => `"${c}"`).join(', ');
    const params = cols.map((c, i) => (c === 'embedding' ? `$${i + 1}::vector` : `$${i + 1}`)).join(', ');

    for (const row of rows) {
      const values = cols.map((c) => {
        const v = row[c];
        if (v === null || v === undefined) return null;
        if (c === 'embedding') return vecLiteral(v);
        if (Buffer.isBuffer(v)) return v;           // raw_data → BYTEA
        return v;
      });
      await pg.query(`INSERT INTO ${table} (${colList}) VALUES (${params})`, values);
    }
    console.log(`  ${table}: ${rows.length} rows copied`);
  }

  // Bump identity sequences past the migrated ids.
  for (const t of IDENTITY_TABLES) {
    await pg.query(`SELECT setval(pg_get_serial_sequence('${t}','id'), COALESCE((SELECT MAX(id) FROM ${t}), 0) + 1, false)`);
  }

  // FK constraints (added post-copy; NOT VALID skipped — data just copied 1:1).
  const fks = [
    `ALTER TABLE companies ADD CONSTRAINT fk_companies_user  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL`,
    `ALTER TABLE sessions  ADD CONSTRAINT fk_sessions_user   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE`,
    `ALTER TABLE chats     ADD CONSTRAINT fk_chats_company   FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE calls     ADD CONSTRAINT fk_calls_company   FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`,
    `ALTER TABLE kb_documents ADD CONSTRAINT fk_kbdocs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE kb_chunks ADD CONSTRAINT fk_kbchunks_doc    FOREIGN KEY (document_id) REFERENCES kb_documents(id) ON DELETE CASCADE`,
    `ALTER TABLE scenarios ADD CONSTRAINT fk_scenarios_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE scenario_versions ADD CONSTRAINT fk_scv_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE`,
    `ALTER TABLE whatsapp_sessions ADD CONSTRAINT fk_wa_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE api_keys  ADD CONSTRAINT fk_apikeys_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE usage_counters ADD CONSTRAINT fk_usage_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
  ];
  for (const fk of fks) {
    try { await pg.query(fk); } catch (e) {
      if (e.code !== '42710' /* duplicate_object */) console.warn(`  FK warn: ${e.message}`);
    }
  }
  console.log('sequences + FKs done');

  // HNSW index for cosine search (builds fast at this scale).
  await pg.query(`CREATE INDEX IF NOT EXISTS idx_kbchunks_embedding
                  ON kb_chunks USING hnsw (embedding vector_cosine_ops)`);
  console.log('pgvector HNSW index ready');

  // ─── Verification 1: row counts ───
  let ok = true;
  for (const table of TABLES) {
    const exists = sq.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(table);
    if (!exists) continue;
    const a = sq.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get().n;
    const b = Number((await pg.query(`SELECT COUNT(*) AS n FROM ${table}`)).rows[0].n);
    const match = a === b;
    ok = ok && match;
    console.log(`  verify ${table}: sqlite=${a} pg=${b} ${match ? '✓' : '✗ MISMATCH'}`);
  }

  // ─── Verification 2: vector search parity ───
  // For sample chunks, pgvector's cosine top-3 must equal the JS cosine
  // top-3 the app computes today.
  const sampleChunks = sq.prepare(`SELECT id, company_id, embedding FROM kb_chunks ORDER BY RANDOM() LIMIT 5`).all();
  if (sampleChunks.length) {
    const { cosine } = require('../lib/rag');
    for (const sample of sampleChunks) {
      const qv = bufferToVec(sample.embedding);
      const all = sq.prepare(`SELECT id, embedding FROM kb_chunks WHERE company_id = ?`).all(sample.company_id);
      const jsTop = all
        .map((r) => ({ id: r.id, score: cosine(qv, bufferToVec(r.embedding)) }))
        .sort((x, y) => y.score - x.score).slice(0, 3).map((r) => r.id);
      const pgTop = (await pg.query(
        `SELECT id FROM kb_chunks WHERE company_id = $1 ORDER BY embedding <=> $2::vector LIMIT 3`,
        [sample.company_id, vecLiteral(sample.embedding)],
      )).rows.map((r) => Number(r.id));
      const match = JSON.stringify(jsTop) === JSON.stringify(pgTop);
      ok = ok && match;
      console.log(`  vector parity (chunk ${sample.id}): js=[${jsTop}] pg=[${pgTop}] ${match ? '✓' : '✗'}`);
    }
  } else {
    console.log('  vector parity: no chunks in source (skipped)');
  }

  sq.close();
  await pg.end();
  console.log(ok ? '\nMIGRATION OK — all verifications passed' : '\nMIGRATION FAILED VERIFICATION');
  process.exit(ok ? 0 : 1);
}

main().catch((e) => { console.error('MIGRATION ERROR:', e.message); process.exit(1); });
