// SQLite → PostgreSQL (+pgvector) migration.
//
// Usage:
//   DATABASE_URL=postgres://... node scripts/migrate-to-pg.js [--sqlite path/to/data.db]
//
// Idempotent full copy: creates the schema (IF NOT EXISTS), TRUNCATEs the
// target tables, copies every row, fixes sequences, adds FK constraints,
// builds the pgvector HNSW index, then VERIFIES:
//   1. row counts match per table
//   2. pgvector cosine top-K matches the current JS cosine top-K for
//      sample embeddings (proves the vector conversion is faithful)
//
// Design notes:
// - Timestamp columns stay TEXT ('YYYY-MM-DD HH:MM:SS', UTC) — identical to
//   SQLite's datetime('now') — so every string-comparison query in the app
//   keeps its exact semantics after cutover.
// - kb_chunks.embedding: BLOB (Float32Array LE) → vector(1536).
// - Serial ids use GENERATED BY DEFAULT AS IDENTITY so migrated rows keep
//   their original ids; sequences are bumped to MAX(id)+1 afterwards.
const path = require('path');
const { Client } = require('pg');
const Database = require('better-sqlite3');

const argSqlite = process.argv.indexOf('--sqlite');
const SQLITE_PATH = argSqlite > -1
  ? process.argv[argSqlite + 1]
  : (process.env.DB_PATH || path.join(__dirname, '..', 'data.db'));
const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error('DATABASE_URL is required'); process.exit(1); }

// TEXT timestamp default identical to SQLite's datetime('now').
const NOW_TEXT = `to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')`;

const DDL = `
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS schema_migrations (
  id          BIGINT PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  applied_at  TEXT NOT NULL DEFAULT ${NOW_TEXT}
);

CREATE TABLE IF NOT EXISTS users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT NOT NULL,
  password_hash   TEXT NOT NULL,
  name            TEXT,
  role            TEXT NOT NULL DEFAULT 'owner',
  failed_logins   BIGINT DEFAULT 0,
  locked_until    TEXT,
  last_login_at   TEXT,
  created_at      TEXT DEFAULT ${NOW_TEXT},
  company_id      TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower ON users (lower(email));

CREATE TABLE IF NOT EXISTS companies (
  id              TEXT PRIMARY KEY,
  user_id         BIGINT,
  name            TEXT NOT NULL,
  language        TEXT DEFAULT 'ar-SA',
  voice_id        TEXT,
  phone_number    TEXT,
  assistant_id    TEXT,
  assistant_id_inbound TEXT,
  system_prompt   TEXT NOT NULL,
  kb_text         TEXT,
  settings        TEXT,
  last_synced_at  TEXT,
  created_at      TEXT DEFAULT ${NOW_TEXT},
  updated_at      TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_companies_user ON companies(user_id);

CREATE TABLE IF NOT EXISTS sessions (
  id           TEXT PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  created_at   TEXT DEFAULT ${NOW_TEXT},
  expires_at   TEXT NOT NULL,
  last_seen_at TEXT,
  user_agent   TEXT,
  ip           TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS auth_events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT,
  email      TEXT,
  event_type TEXT NOT NULL,
  ip         TEXT,
  user_agent TEXT,
  created_at TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_auth_events_user ON auth_events(user_id);

CREATE TABLE IF NOT EXISTS chats (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id    TEXT NOT NULL,
  session_id    TEXT NOT NULL,
  user_message  TEXT NOT NULL,
  assistant_reply TEXT,
  channel       TEXT DEFAULT 'text',
  latency_ms    BIGINT,
  summary       TEXT,
  user_id       BIGINT,
  created_at    TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_chats_company ON chats(company_id);
CREATE INDEX IF NOT EXISTS idx_chats_session ON chats(session_id);
CREATE INDEX IF NOT EXISTS idx_chats_created ON chats(created_at);
CREATE INDEX IF NOT EXISTS idx_chats_company_created ON chats(company_id, created_at);

CREATE TABLE IF NOT EXISTS calls (
  id              TEXT PRIMARY KEY,
  company_id      TEXT,
  assistant_id    TEXT,
  caller_number   TEXT,
  duration_sec    BIGINT,
  started_at      TEXT,
  ended_at        TEXT,
  ended_reason    TEXT,
  transcript      TEXT,
  summary         TEXT,
  cost_usd        DOUBLE PRECISION,
  direction       TEXT NOT NULL DEFAULT 'inbound',
  recording_url   TEXT,
  created_at      TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_calls_company ON calls(company_id);
CREATE INDEX IF NOT EXISTS idx_calls_direction ON calls(direction);
CREATE INDEX IF NOT EXISTS idx_calls_created ON calls(created_at);
CREATE INDEX IF NOT EXISTS idx_calls_company_created ON calls(company_id, created_at);

CREATE TABLE IF NOT EXISTS kb_documents (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   TEXT NOT NULL,
  filename     TEXT NOT NULL,
  mime_type    TEXT,
  size_bytes   BIGINT,
  raw_text     TEXT,
  raw_data     BYTEA,
  deleted_at   TEXT,
  created_at   TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_kbdocs_company ON kb_documents(company_id);

CREATE TABLE IF NOT EXISTS kb_chunks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id    TEXT NOT NULL,
  document_id   BIGINT NOT NULL,
  chunk_index   BIGINT NOT NULL,
  text          TEXT NOT NULL,
  embedding     vector(1536) NOT NULL,
  token_count   BIGINT,
  created_at    TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_kbchunks_company ON kb_chunks(company_id);
CREATE INDEX IF NOT EXISTS idx_kbchunks_doc     ON kb_chunks(document_id);

CREATE TABLE IF NOT EXISTS audit_events (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id     BIGINT,
  actor_email  TEXT,
  action       TEXT NOT NULL,
  resource     TEXT,
  metadata     TEXT,
  ip           TEXT,
  user_agent   TEXT,
  created_at   TEXT DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_audit_actor  ON audit_events(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_events(action);

CREATE TABLE IF NOT EXISTS usage_counters (
  company_id   TEXT NOT NULL,
  day          TEXT NOT NULL,
  kind         TEXT NOT NULL,
  amount       BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (company_id, day, kind)
);

CREATE TABLE IF NOT EXISTS webhook_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider      TEXT NOT NULL,
  event_id      TEXT,
  event_type    TEXT,
  raw_body      TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  attempts      BIGINT NOT NULL DEFAULT 0,
  last_error    TEXT,
  received_at   TEXT NOT NULL DEFAULT ${NOW_TEXT},
  processed_at  TEXT,
  UNIQUE (provider, event_id)
);
CREATE INDEX IF NOT EXISTS idx_webhook_events_status ON webhook_events(status);

CREATE TABLE IF NOT EXISTS scenarios (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          TEXT NOT NULL,
  name                TEXT NOT NULL,
  description         TEXT,
  first_message       TEXT,
  first_message_inbound TEXT,
  instruction_prompt  TEXT NOT NULL,
  instruction_prompt_inbound TEXT,
  success_criteria    TEXT,
  variables           TEXT,
  is_active           BIGINT NOT NULL DEFAULT 1,
  language            TEXT DEFAULT 'ar',
  knowledge_base_ids  TEXT,
  created_at          TEXT DEFAULT ${NOW_TEXT},
  updated_at          TEXT DEFAULT ${NOW_TEXT},
  deleted_at          TEXT
);
CREATE INDEX IF NOT EXISTS idx_scenarios_company ON scenarios(company_id);
CREATE INDEX IF NOT EXISTS idx_scenarios_active  ON scenarios(company_id, is_active, deleted_at);

CREATE TABLE IF NOT EXISTS scenario_versions (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_id            BIGINT NOT NULL,
  name                   TEXT,
  first_message          TEXT,
  first_message_inbound  TEXT,
  instruction_prompt     TEXT,
  edited_by              TEXT,
  created_at             TEXT NOT NULL DEFAULT ${NOW_TEXT}
);
CREATE INDEX IF NOT EXISTS idx_scenario_versions_sc ON scenario_versions(scenario_id, created_at DESC);

CREATE TABLE IF NOT EXISTS whatsapp_sessions (
  company_id     TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  vapi_chat_id   TEXT,
  updated_at     TEXT NOT NULL DEFAULT ${NOW_TEXT},
  PRIMARY KEY (company_id, customer_phone)
);

CREATE TABLE IF NOT EXISTS api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   TEXT NOT NULL,
  name         TEXT,
  key_hash     TEXT NOT NULL UNIQUE,
  prefix       TEXT NOT NULL,
  created_at   TEXT NOT NULL DEFAULT ${NOW_TEXT},
  last_used_at TEXT,
  revoked_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_api_keys_company ON api_keys(company_id);
`;

// Tables in copy order (no FK constraints during copy; added after).
const TABLES = [
  'schema_migrations', 'users', 'companies', 'sessions', 'auth_events',
  'chats', 'calls', 'kb_documents', 'kb_chunks', 'audit_events',
  'usage_counters', 'webhook_events', 'scenarios', 'scenario_versions',
  'whatsapp_sessions', 'api_keys',
];

// Serial-id tables that need their sequence bumped after explicit-id inserts.
const IDENTITY_TABLES = ['users', 'auth_events', 'chats', 'kb_documents',
  'kb_chunks', 'audit_events', 'webhook_events', 'scenarios',
  'scenario_versions', 'api_keys'];

function bufferToVec(buf) {
  return new Float32Array(buf.buffer, buf.byteOffset, buf.length / 4);
}
function vecLiteral(buf) {
  const v = bufferToVec(buf);
  // Full float precision — cosine parity with the JS implementation.
  return '[' + Array.from(v).join(',') + ']';
}

async function main() {
  console.log(`SQLite source : ${SQLITE_PATH}`);
  const sq = new Database(SQLITE_PATH, { readonly: true });
  const pg = new Client({ connectionString: DATABASE_URL });
  await pg.connect();
  console.log('Postgres connected');

  await pg.query(DDL);
  console.log('schema created');

  // Fresh copy every run (idempotent). CASCADE clears dependent rows.
  await pg.query(`TRUNCATE ${TABLES.join(', ')} CASCADE`);

  for (const table of TABLES) {
    const exists = sq.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(table);
    if (!exists) { console.log(`  ${table}: not in source, skipped`); continue; }
    const rows = sq.prepare(`SELECT * FROM ${table}`).all();
    if (!rows.length) { console.log(`  ${table}: 0 rows`); continue; }

    const cols = Object.keys(rows[0]);
    const colList = cols.map((c) => `"${c}"`).join(', ');
    const params = cols.map((c, i) => (c === 'embedding' ? `$${i + 1}::vector` : `$${i + 1}`)).join(', ');

    for (const row of rows) {
      const values = cols.map((c) => {
        const v = row[c];
        if (v === null || v === undefined) return null;
        if (c === 'embedding') return vecLiteral(v);
        if (Buffer.isBuffer(v)) return v;           // raw_data → BYTEA
        return v;
      });
      await pg.query(`INSERT INTO ${table} (${colList}) VALUES (${params})`, values);
    }
    console.log(`  ${table}: ${rows.length} rows copied`);
  }

  // Bump identity sequences past the migrated ids.
  for (const t of IDENTITY_TABLES) {
    await pg.query(`SELECT setval(pg_get_serial_sequence('${t}','id'), COALESCE((SELECT MAX(id) FROM ${t}), 0) + 1, false)`);
  }

  // FK constraints (added post-copy; NOT VALID skipped — data just copied 1:1).
  const fks = [
    `ALTER TABLE companies ADD CONSTRAINT fk_companies_user  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL`,
    `ALTER TABLE sessions  ADD CONSTRAINT fk_sessions_user   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE`,
    `ALTER TABLE chats     ADD CONSTRAINT fk_chats_company   FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE calls     ADD CONSTRAINT fk_calls_company   FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL`,
    `ALTER TABLE kb_documents ADD CONSTRAINT fk_kbdocs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE kb_chunks ADD CONSTRAINT fk_kbchunks_doc    FOREIGN KEY (document_id) REFERENCES kb_documents(id) ON DELETE CASCADE`,
    `ALTER TABLE scenarios ADD CONSTRAINT fk_scenarios_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE scenario_versions ADD CONSTRAINT fk_scv_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE`,
    `ALTER TABLE whatsapp_sessions ADD CONSTRAINT fk_wa_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE api_keys  ADD CONSTRAINT fk_apikeys_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
    `ALTER TABLE usage_counters ADD CONSTRAINT fk_usage_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE`,
  ];
  for (const fk of fks) {
    try { await pg.query(fk); } catch (e) {
      if (e.code !== '42710' /* duplicate_object */) console.warn(`  FK warn: ${e.message}`);
    }
  }
  console.log('sequences + FKs done');

  // HNSW index for cosine search (builds fast at this scale).
  await pg.query(`CREATE INDEX IF NOT EXISTS idx_kbchunks_embedding
                  ON kb_chunks USING hnsw (embedding vector_cosine_ops)`);
  console.log('pgvector HNSW index ready');

  // ─── Verification 1: row counts ───
  let ok = true;
  for (const table of TABLES) {
    const exists = sq.prepare(`SELECT 1 FROM sqlite_master WHERE type='table' AND name=?`).get(table);
    if (!exists) continue;
    const a = sq.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get().n;
    const b = Number((await pg.query(`SELECT COUNT(*) AS n FROM ${table}`)).rows[0].n);
    const match = a === b;
    ok = ok && match;
    console.log(`  verify ${table}: sqlite=${a} pg=${b} ${match ? '✓' : '✗ MISMATCH'}`);
  }

  // ─── Verification 2: vector search parity ───
  // For sample chunks, pgvector's cosine top-3 must equal the JS cosine
  // top-3 the app computes today.
  const sampleChunks = sq.prepare(`SELECT id, company_id, embedding FROM kb_chunks ORDER BY RANDOM() LIMIT 5`).all();
  if (sampleChunks.length) {
    const { cosine } = require('../lib/rag');
    for (const sample of sampleChunks) {
      const qv = bufferToVec(sample.embedding);
      const all = sq.prepare(`SELECT id, embedding FROM kb_chunks WHERE company_id = ?`).all(sample.company_id);
      const jsTop = all
        .map((r) => ({ id: r.id, score: cosine(qv, bufferToVec(r.embedding)) }))
        .sort((x, y) => y.score - x.score).slice(0, 3).map((r) => r.id);
      const pgTop = (await pg.query(
        `SELECT id FROM kb_chunks WHERE company_id = $1 ORDER BY embedding <=> $2::vector LIMIT 3`,
        [sample.company_id, vecLiteral(sample.embedding)],
      )).rows.map((r) => Number(r.id));
      const match = JSON.stringify(jsTop) === JSON.stringify(pgTop);
      ok = ok && match;
      console.log(`  vector parity (chunk ${sample.id}): js=[${jsTop}] pg=[${pgTop}] ${match ? '✓' : '✗'}`);
    }
  } else {
    console.log('  vector parity: no chunks in source (skipped)');
  }

  sq.close();
  await pg.end();
  console.log(ok ? '\nMIGRATION OK — all verifications passed' : '\nMIGRATION FAILED VERIFICATION');
  process.exit(ok ? 0 : 1);
}

main().catch((e) => { console.error('MIGRATION ERROR:', e.message); process.exit(1); });
